### PR TITLE
Fix parser when SCIM begins with a NOT and add more tests

### PR DESCRIPTION
**Pull request by shaneshen-okta**
- Fix parser when SCIM begins with a NOT, issue [#55](https://github.com/thomaspoignant/scim2-parse-filter/issues/55) 
- Fix stringfy for `and` op
- Add more tests

### CODE REVIEW

**Comment by thomaspoignant** [comment]
Thanks @shaneshen-okta for your pull request this awesome.
I will have a closer look soon and if everything is ok I will merge it and release a new version.

**Review by thomaspoignant — APPROVED** [review]
LGTM thanks a lot for your contribution.

**Comment by thomaspoignant** [comment]
@shaneshen-okta the version `0.2.5` with your fix is available on npm.

**Comment by shaneshen-okta** [comment]
@thomaspoignant that's great. Thanks for the quick response.

**Pull request merged**
