### PR TITLE
fix stringfy

### PR DESCRIPTION
**Pull request by shaneshen-okta**
🔴 `stringfy` dose NOT return correct string for certain filters, see [test case](https://github.com/thomaspoignant/scim2-parse-filter/pull/92/commits/31c3ed3e2abac678e65f98e5ecf7fd4fe8b14343)

✅ clean `stringfy` and add fix

### CODE REVIEW

**Comment by thomaspoignant** [comment]
@shaneshen-okta thanks for your pull request I am on PTO and don't have access to a computer until next week.

I will have a look as soon as I am back and release a new version based on that.

**Comment by shaneshen-okta** [comment]
@thomaspoignant  sure, have fun.

**Comment by shaneshen-okta** [comment]
@thomaspoignant No mean to rush. just a gentle reminder on this PR in case you forget. thanks

**Comment by thomaspoignant** [comment]
I have released a new version with this fix.
You can find version `0.2.6` on npm.

**Comment by shaneshen-okta** [comment]
@thomaspoignant that's awesome. thanks

**Pull request merged**
