### PR TITLE
New Feature: stringify

### LINKED ISSUE #45: Feature Request: Stringify (reverse transform of parse)
Would you be interested in adding the reverse transform of parse? Such that given a scim AST as returned by parse() it would return the string that would generate it?

The use case I have is that I want to make a scim filter wizard that makes it easier for a non-technical person to write a scim filter string using dropdowns and text fields. This library works great for transforming the string representation into the AST, but not the reverse which I need.

Not necessarily asking the maintainers to do the work, just asking if a feature like this would be acceptable / mergeable into this library.

### PR DESCRIPTION
**Pull request by patrickmcdougle-okta**
This PR introduces a new function called stringify which when given a Filter returns the scim string representation of that filter. It is a reverse transform of the parse function.

Tangents:
- I could not get the tests to pass in watch mode...something that I didn't understand about typescript + commonjs imports/exports. It doesn't seem to think that stringify is a function in my test file. Feedback welcome on how to fix this.
- The test file is almost a complete reproduction of the test for parse, swapping out the test function. One test needed to be changed because it contained vestigial parenthesis which stringify did not generate, so they were removed from the expected output. Please let me know if you want me to make a change to keep this more DRY. I just didn't want to do too much mucking around without your permission.
- Let me know if you want me to doc this feature in the readme.

I'm not an expert in scim, so I can't promise there aren't any bugs here, but if anyone finds them, I'd be happy to try and figure them out. For what it's worth my implementation is pretty close to the toString methods of the models in [this Java package](https://github.com/pingidentity/scim2/tree/master/scim2-sdk-common/src/main/java/com/unboundid/scim2/common/filters).

Fixes #45

### CODE REVIEW

**Comment by patrickmcdougle-okta** [comment]
^ lol, told you the tests were almost identical 😄

**Comment by patrickmcdougle-okta** [comment]
One possible bug already: the compValue needs to be JSON stringified instead of always literally quoted.

**Comment by patrickmcdougle-okta** [comment]
@thomaspoignant please let me know how I should proceed with removing the duplication as specified by SonarCloud. Also let me know if you want me to squash my commits or have any code review feedback. Thanks!

**Comment by thomaspoignant** [comment]
Thanks a lot for the addition I will check it as soon as possible.
Don't worries about the duplication if it is in the test file, I will change the policy in sonarcloud to avoid that warning.

I'll try to review it during the week end or on Monday.

**Comment by patrickmcdougle-okta** [comment]
Thanks. Sorry for pinging you directly, I wasn't sure if just opening the PR was enough for you to get a notification.

**Comment by thomaspoignant** [comment]
I've committed some fix to make `watch` works again.

> One possible bug already: the compValue needs to be JSON stringified instead of always literally quoted.
What do you mean by that? I am not sure to understand exactly what you mean?

**Comment by patrickmcdougle-okta** [comment]
We don't have to worry about the JSON stringify bug. I fixed the issue in 0a85e0a49b2a52837a25c66b538fc73b2b1968c4.

I'm about to push up one more commit fixing a bug in flattened ASTs (for example if AND has more than 2 filters).

**Review by thomaspoignant — COMMENTED** [review]
This sounds all good to me.
The only missing part is to edit the `README.md` to explain this new feature. Can you do it?

**Comment by patrickmcdougle-okta** [comment]
Yes, I can do this a little later today.

**Comment by patrickmcdougle-okta** [comment]
Done! Let me know if you need anything else from me. Do you need me to squash my commits?

**Comment by thomaspoignant** [comment]
No that’s perfect thank you 🙏🏻 
This is awesome 🤩

**Pull request merged**
